# Generated by Django 3.0.3 on 2020-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=300)),
                ('contact_email', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
