# Generated by Django 3.0.3 on 2020-02-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
