# Generated by Django 3.0.3 on 2020-02-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_contactforminfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormInfo',
        ),
    ]
