# Generated by Django 3.0.3 on 2020-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_contactforminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactforminfo',
            name='student_age',
            field=models.IntegerField(max_length=300),
        ),
    ]
