# Generated by Django 3.0.3 on 2020-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20200225_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorContactFormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=300)),
                ('tutor_subject', models.CharField(max_length=300)),
                ('tutor_level', models.IntegerField(max_length=300)),
                ('tutor_email', models.CharField(max_length=300)),
            ],
        ),
    ]
